name: Hello world
on: 
  workflow_dispatch:
  schedule:
        - cron: '*/10 * * * *'


jobs:
  # the id of the name
  hello-world-job: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out the repository
    - uses: actions/checkout@v3 
    # Runs a single command using the runner shell
    - name: Run a one-line script
      run: echo "hello world"
      
  flip-job:
    needs: hello-world-job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out the repository
    - uses: actions/checkout@v3 
    # Runs a single command using the runner shell
    - name: Run a one-line script
      run: echo "Do a flip"
      
  flop-job:
    needs: hello-world-job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out the repository
    - uses: actions/checkout@v3 
    # Runs a single command using the runner shell
    - name: Run a one-line script
      run: echo "Do a flop"
      
